default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["TALENTARI_USERNAME"] %>
  password: <%= ENV["TALENTARI_PASSWORD"] %>
  host: localhost

development:
  <<: *default
  database: talentari_development

test:
  <<: *default
  database: talentari_test

production:
  primary: &primary_production
    <<: *default
    database: talentari_production
    username: <%= ENV["TALENTARI_USERNAME"] %>
    password: <%= ENV["TALENTARI_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: talentari_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: talentari_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: talentari_production_cable
    migrations_paths: db/cable_migrate
